### PR TITLE
update the sbl_cd build in device-intel-build repo

### PR DESCRIPTION
**Pull request by bhe4**

### CODE REVIEW

**Review by GangSecurity — COMMENTED** [review]
Add Traceked-On

**Review by JeevakaPrabu — CHANGES_REQUESTED** [review]
please make sure the commit summary is only one line and <72 characters
Add Tests done: to commit message

**Review by JeevakaPrabu — CHANGES_REQUESTED** [review]
please make sure the commit summary is only one line and <72 characters
Add Tests done: to commit message

**Review by dyang23 — APPROVED** [review]
LGTM

**Review by dyang23 — APPROVED** [review]
LGTM

**Review by dyang23 — APPROVED** [review]
LGTM

**Review by GangSecurity — APPROVED** [review]

**Review by bing8deng — APPROVED** [review]

**Review by JeevakaPrabu — APPROVED** [review]

**Pull request merged**
